name: Pull Request Workflow

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: mvn clean test
